### ISSUE TITLE
Для push лучше не парсить строку подключения а переопределять переменную GIT_ASKPASS

### ISSUE THREAD

**Issue by pumbaEO** [1C-Company/GitConverter#10]
Для возможности указания параметров подключения к гит серверу можно использовать переопределение переменнй GIT_ASKPASS с указанием пути к временному файлу, который выглядит примерно так:
windows:
```
@set arg=%~1
@if (%arg:~0,8%)==(Username) echo  myusername
@if (%arg:~0,8%)==(Password) echo mypassw
```
для linux:
```
#!/bin/sh"
case "$1" in
Username*) echo 'myusername';;
assword*) echo 'mypassw';;
esac
```

**Comment by marmyshev** [comment]
Кажется, что не очень актуально, и реквестов нет. Если планируешь контрибутить такой вариант открывай снова...
