### ISSUE TITLE
Зависание 1cv8 при создании базы на 8.3.14 в случае повторного запуска

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/GitConverter#103]
**Описание ошибки**
При переходе на платформу `8.3.14` в случае, если операция получения версии из хранилища в прошлый раз выполнялась неуспешно, то повторный запуск "получения версии" приводит к зависанию процесса `1cv8`.

**Способ обхода**
Ошибка возникает из-за наличия базы в "списке баз" `ibases.v8i`, созданной в предыдущий  неуспешный запуск. Достаточно удалить файл `ibases.v8i` или настроить авто-удаление [по инструкции](https://github.com/1C-Company/GitConverter/wiki/Настройка-сервера-1С#Удаление-файла-списка-версий-ibasesv8i) - тогда обработка версии продолжится как обычно.

**Ожидаемое поведение**

> В документацию и справку конфигуратора внесено описание ключей /Out, /L, /VL и /O для режима запуска CREATEINFOBASE, которые ранее были не описаны.
Для режима запуска в режиме создания информационной базы (CREATEINFOBASE) реализован ключ командной строки /DumpResult, записывающий в файл результат работы. При использовании в пакетном режиме запуска конфигуратора (в файловом варианте) ключей /RestoreIB и /LoadCfg вместе с ключом /DisableStartupDialogs, информационная база будет автоматически создана, если в каталоге отсутствует файл с базой данных.
>
> Источник: https://dl04.1c.ru/content/Platform/8_3_15_1489/1cv8upd_8_3_15_1489.htm#55870eaa-7bf2-11e5-a3f7-0050569f678a

Для режима `CREATEINFOBASE` ранее не требовалось указывать параметр `/DisableStartupDialogs`. Теперь этот флаг влияет на появление интерактивных окон в режиме создания и совместно с добавленным честным результатом в `/DumpResult` добавление базы в список если уже существует - является "неуспешной" операцией и требует ответа пользователя интерактивно. На Платформе `8.3.12` и ранее - такого поведения не наблюдалось, несмотря на то, что в "Новом в версии" указаное изменение сделано для 8.3.8.

**Comment by VladFrost** [comment]
Я, наверное, тоже на этот баг наткнулся: конвертация зависла. Интуитивно стал чистить кэши и biases.v8i и это помогло. А, оказывается, вон оно что!
