### ISSUE TITLE
При импорте родительского объекта произошла ошибка

### ISSUE THREAD

**Issue by mrdenchik** [1C-Company/GitConverter#105]
При попытке загрузки метаданных версии хранилища в логах появляется ошибка:
25.07.2019 9:59:02 Начало импорта в 1C:EDT
Debug options:
    file:/opt/1C/1CE/components/1c-edt-1.11.0+528-x86_64/.options loaded
Warning: NLS unused message: LaunchConfigurationWorkingCopy_8 in: org.eclipse.debug.internal.core.DebugCoreMessages
Операция импорта проекта завершена неуспешно.
По причине: Во время выполнения операции импорта произошло несколько ошибок
Произошла непредвиденная ошибка при импорте файла "ChartsOfAccounts/бит_Бюджетирование/Forms/ФормаВыбораУправляемая/Ext/Form.xml"
Произошла непредвиденная ошибка при импорте файла "ChartsOfAccounts/бит_Дополнительный_2/Forms/ФормаВыбораУправляемая/Ext/Form.xml"
Ошибка импорта файла "ChartsOfAccounts/бит_Бюджетирование/Forms/ФормаВыбораУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Ошибка импорта файла "ChartsOfAccounts/бит_Дополнительный_2/Forms/ФормаВыбораУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Произошла непредвиденная ошибка при импорте файла "DataProcessors/ВводНачальныхОстатков/Forms/Форма/Ext/Form.xml"
Ошибка импорта файла "DataProcessors/ВводНачальныхОстатков/Forms/Форма/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Произошла непредвиденная ошибка при импорте файла "Documents/бит_вго_АктСверкиВГО/Forms/ФормаДокументаУправляемая/Ext/Form.xml"
Ошибка импорта файла "Documents/бит_вго_АктСверкиВГО/Forms/ФормаДокументаУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Ошибка выполнения процесса 1C:Enterprise Development Tools.
25.07.2019 9:59:56 Окончание импорта в 1C:EDT
Код возврата: 1

Конфигурация БИТ.Финанс доработанная, ОС Debian 9.9, версия 1С 8.3.13.1690, EDT 1.11

**Comment by marmyshev** [comment]
## Способ обхода

Чтобы быстро обойти эту ошибку (временное решение) - достаточно сделать следующее:
1. Отключить "Выгрузку изменений" в карточке настройки хранилища
2. в списке версий, для которой произошла эта ошибка - в контекстном меню - сбросе состояние версии до "Версия получена".

Т.о. версия выгрузится полностью и загрузится полностью в EDT без таких ошибок.

## Нужна доп. инфа чтобы разобраться в ошибке

1. пришлите все файлы лежащие в директории версии в корне.
2. Пришлите список файлов выгрузки (листинг) в директории /path_to_dump/342/dump - когда происходит выгрузка изменений Конфигуратор выгружает ровно те файлы которые были изменены. НО для EDT нужны выгруженные все файлы объектов-родителей. Например, при выгрузке `ChartsOfAccounts/бит_Дополнительный_2/Forms/ФормаВыбораУправляемая/Ext/Form.xml` еще должны быть файлы `ChartsOfAccounts/бит_Дополнительный_2.xml` и все подчиненные файлы в каталоге `ChartsOfAccounts/бит_Дополнительный_2` - это нужно для корректного импорта в EDT. до выгрузка родителей выполняется командой Конфигуратора после выгрузки изменений - файлы лежат в коре версии.

**Comment by mrdenchik** [comment]
Способ обхода не помог. Та же ошибка. 
Было создано новое хранилище, первая же версия(полная) выдает эту ошибку.
Приложил скриншоты со список файлов. 

![ChartsOfAccounts](https://user-images.githubusercontent.com/39699708/62204296-9c94b080-b395-11e9-9a6b-c27f60dceb81.png)
![Dump](https://user-images.githubusercontent.com/39699708/62204138-40ca2780-b395-11e9-85cc-5f7c6cfa2de4.png)
![КореньВерсии](https://user-images.githubusercontent.com/39699708/62204139-40ca2780-b395-11e9-822a-f3a6b92d02c2.png)

**Comment by mrdenchik** [comment]
Заметил одну особенность: у нас GitConverter работает на Debian 9.9 без GUI, используем Fake Xserver xvfb-run. Для этого в конфигурации внесли небольшие изменения, типа
`СтрокаКоманды = "bash -c ""/usr/bin/xvfb-run -a " + СтрЗаменить(СтрокаКоманды,"""","") + """";`.
Рандомным образом получаем ошибку выше.
При этом если запустить команду в Ubuntu 18.04 Desktop (с GUI) - ошибки нет.

**Comment by marmyshev** [comment]
> Приложил скриншоты со список файлов.

Я изначально сделал предположение, что проблема из-за "выгрузки изменений". Но судя по выгрузке - она полная, и способ обхода, описанный выше, тут ни при чем. Собственно, файла `diff.txt` в котором список изменений - нет.

> у нас GitConverter работает на Debian 9.9 без GUI, используем Fake Xserver xvfb-run. Для этого в конфигурации внесли небольшие изменения, типа
СтрокаКоманды = "bash -c ""/usr/bin/xvfb-run -a " + СтрЗаменить(СтрокаКоманды,"""","") + """";.

Предполагалось, что команду `/usr/bin/xvfb-run -a /opt/1cv8/bin/1cv8` нужно прописывать в константе "Путь к версиям платформы на сервере".

> Рандомным образом получаем ошибку выше.
> При этом если запустить команду в Ubuntu 18.04 Desktop (с GUI) - ошибки нет.

Можете провести эксперимент:
1. Выполните импорт текущей полной выгрузки в EDT в режиме без GUI из консоли `ring edt workspace import ...` как тут https://github.com/1C-Company/GitConverter/blob/master/GitConverter/src/CommonModules/КонвертацияХранилища/Module.bsl#L1422 если возникает ошибка - значит в EDT теперь что-то зависит от UI при импорте (хотя раньше не было).
2. Выполните импорт текущей выгрузки через `/usr/bin/xvfb-run -a ring edt workspace import ...` - если ошибки стабильно нет - то пока, как временное решение, можно стартовать весь сервер 1С через `xvfb-run` тогда каждая команда будет выполняться в UI.

**Comment by mrdenchik** [comment]
root@srvr:~/tmp# **ring edt workspace import --workspace-location "/root/tmp/base/ws/" --configuration-files "/root/tmp/base/dump/" --project "/root/tmp/base/p/" --version 8.3.13**
Debug options:
    file:/opt/1C/1CE/components/1c-edt-1.11.0+528-x86_64/.options loaded
Warning: NLS unused message: LaunchConfigurationWorkingCopy_8 in: org.eclipse.debug.internal.core.DebugCoreMessages
Операция импорта проекта завершена неуспешно.
По причине: Во время выполнения операции импорта произошло несколько ошибок
Произошла непредвиденная ошибка при импорте файла "ChartsOfAccounts/бит_Дополнительный_2/Forms/ФормаВыбораУправляемая/Ext/Form.xml"
Ошибка импорта файла "ChartsOfAccounts/бит_Дополнительный_2/Forms/ФормаВыбораУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Произошла непредвиденная ошибка при импорте файла "ChartsOfAccounts/бит_Бюджетирование/Forms/ФормаВыбораУправляемая/Ext/Form.xml"
Ошибка импорта файла "ChartsOfAccounts/бит_Бюджетирование/Forms/ФормаВыбораУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Произошла непредвиденная ошибка при импорте файла "DataProcessors/ВводНачальныхОстатков/Forms/Форма/Ext/Form.xml"
Ошибка импорта файла "DataProcessors/ВводНачальныхОстатков/Forms/Форма/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Произошла непредвиденная ошибка при импорте файла "Documents/бит_вго_АктСверкиВГО/Forms/ФормаДокументаУправляемая/Ext/Form.xml"
Ошибка импорта файла "Documents/бит_вго_АктСверкиВГО/Forms/ФормаДокументаУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Ошибка выполнения процесса 1C:Enterprise Development Tools.
root@srvr:~/tmp# **/usr/bin/xvfb-run -a ring edt workspace import --workspace-location "/root/tmp/base/ws/" --configuration-files "/root/tmp/base/dump/" --project "/root**/tmp/base/p/" --version 8.3.13
Debug options:
    file:/opt/1C/1CE/components/1c-edt-1.11.0+528-x86_64/.options loaded
Warning: NLS unused message: LaunchConfigurationWorkingCopy_8 in: org.eclipse.debug.internal.core.DebugCoreMessages
Операция импорта проекта завершена неуспешно.
По причине: Во время выполнения операции импорта произошло несколько ошибок
Произошла непредвиденная ошибка при импорте файла "ChartsOfAccounts/бит_Бюджетирование/Forms/ФормаВыбораУправляемая/Ext/Form.xml"
Произошла непредвиденная ошибка при импорте файла "ChartsOfAccounts/бит_Дополнительный_2/Forms/ФормаВыбораУправляемая/Ext/Form.xml"
Ошибка импорта файла "ChartsOfAccounts/бит_Дополнительный_2/Forms/ФормаВыбораУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Ошибка импорта файла "ChartsOfAccounts/бит_Бюджетирование/Forms/ФормаВыбораУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Произошла непредвиденная ошибка при импорте файла "DataProcessors/ВводНачальныхОстатков/Forms/Форма/Ext/Form.xml"
Ошибка импорта файла "DataProcessors/ВводНачальныхОстатков/Forms/Форма/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Произошла непредвиденная ошибка при импорте файла "Documents/бит_вго_АктСверкиВГО/Forms/ФормаДокументаУправляемая/Ext/Form.xml"
Ошибка импорта файла "Documents/бит_вго_АктСверкиВГО/Forms/ФормаДокументаУправляемая/Ext/Form/Module.bsl"
При импорте родительского объекта произошла ошибка
Ошибка выполнения процесса 1C:Enterprise Development Tools.

К сожалению, оба варианта выдали ошибку. Написал в техподдержку 1С, буду ждать ответа.
Спасибо за помощь!

**Comment by mrdenchik** [comment]
Техподдержка 1С молчит, но мне все таки удалось избавиться от этой ошибки:
1. Удалил полностью EDT.
2. Поставил последнюю на текущий момент версию EDT 1.12.0.221.
3. Поставил менджер окон openbox.

После этого версии загружаются без ошибок.
