### ISSUE TITLE
Сборка расширений

### ISSUE THREAD

**Issue by yehorh** [1C-Company/GitConverter#106]
Есть описание сборки проекта из исходников.

Хотелось бы чтоб была описана сборка и расширения в README.md

**Comment by marmyshev** [comment]
Сборка расширения ни чем практически не отличается от сборки конфигурации (выгрузил-загрузил, сохранил cfe).
Поясните, для чего это "хочется"? чтобы не читать документацию по Платформе?

**Comment by yehorh** [comment]
Да, логично, спасибо за пояснения.
Хотелось просто более дружественной к новичкам инструкции.
Я например подумал что после того что указано в секции `Сборка и установка проекта`
У меня будет собран проект и все расширения какие лежат внутри, рекурсивно.

Конечно инструкции не отменяют необходимость в чтении документации

**Comment by marmyshev** [comment]
Мысль понятна.
Давайте добавим в документацию или ридми.

**Comment by marmyshev** [comment]
Сделал пример сборки расширений
https://github.com/1C-Company/GitConverter/commit/45391ba60a1bab96bf7921f9d6044a4c2f9b7a21
