### ISSUE TITLE
Ошибка при получении номера версии

### ISSUE THREAD

**Issue by feelleen** [1C-Company/GitConverter#112]
Справочник ВерсииХранилища, модуль менеджера. Строка 168:
`Версия = Число(ВерсияХранилища.Версия);`

У меня в ВерсияХранилища.Версия сидит строка "7 850". Соответственно, преобразование к числу невозможно. У себя сделал через СтрЗаменить(ВерсияХранилища.Версия, " ", ""). В исходниках стоит поправить место, где записывается версия. В хранилище конфигурации 1С версия-то всегда числовая.

**Comment by leemuar** [comment]
Эта проблема уже была описана в #45
Как и предлагали в той ветке - если уж и делать, то делать универально, для всех форматов чисел.

**Comment by feelleen** [comment]
> Эта проблема уже была описана в #45
> Как и предлагали в той ветке - если уж и делать, то делать универально, для всех форматов чисел.

Извиняюсь. Не ознакомился с историей :)
