### ISSUE TITLE
ГИТ конвертер, работающий на сервере, помещает commit'ы на GitLab в неверной кодировке

### ISSUE THREAD

**Issue by yegor-novinsky** [1C-Company/GitConverter#113]
Добрый!
Проблема практически описана в заголовке. Когда конфигурация push'илась файловым вариантом базы, имя пользователя Хранилища (русскими буквами) и русскоязычные комментарии выгружались нормально - клиент запускался от . Сейчас, когда перенес **_эту же базу_** Гит конвертера на сервер 1С:Предприятие (версия 8.3.12.1595, версия SQL сервера 13.0.5598.27, ОС Windows Server 2016 Standard), имя пользователя и комментарии push'атся в том виде, который приведен на приложенной к данному сообщению картинке. Home location пользователя, от имени которого работает служба 1С:Предприятие - Russia.
![Screenshot_GitLab](https://user-images.githubusercontent.com/20304311/72887951-b51acd80-3d1d-11ea-9e1b-7f0206000b8c.jpg)

**Comment by VnGNL** [comment]
Добрый день.

У себя разрешил подобную ситуацию заменой в конфигурации гит-конвертера всех случаев **КодировкаТекста.UTF8** на **"CESU-8"**.
