### ISSUE TITLE
Не проходит загрузка, если изменены только интерфейсы

### ISSUE THREAD

**Issue by kwazispb** [1C-Company/GitConverter#116]
**Существует проблема**
Конфигурация на обычных формах. В версии хранилища изменены только интерфейсы. В хранилище включена выгрузка изменений. При загрузке дампа папка src не создается в каталоге p. В итоге  получаем ошибку фонового задания: 
{ОбщийМодуль.КонвертацияХранилища.Модуль(1530)}: Ошибка при вызове метода контекста (КопироватьФайл)
по причине:
Ошибка копирования файлов
по причине:
Ошибка копирования файлов из 'D:\LOGS\v2\3727\ConfigDumpInfo.xml' в 'D:\LOGS\v2\3727\p\UT\src\ConfigDumpInfo.xml' : Каталог не обнаружен

**Хотелось бы иметь следующую функциональность**
Надо пропускать такие релизы хранилища. Не выполнять загрузку и коммит по ним.

**Расширение или улучшение?**

Это улучшение конфигурации 1С:ГитКонвертер потому что [...]

Это функциональность можно реализовать в расширении.

**Дополнительный контекст**
Любая дополнительная информация

**Comment by marmyshev** [comment]
А что в результате выгрузки вы ожидаете? что коммитить в репу? или просто чтобы не падало?

**Comment by kwazispb** [comment]
> А что в результате выгрузки вы ожидаете? что коммитить в репу? или просто чтобы не падало?

Второй вариант
