### ISSUE TITLE
Синтаксическая ошибка в описании ошибки подключения к удаленной репе

### ISSUE THREAD

**Issue by NikitaMikhaylovSB** [1C-Company/GitConverter#117]
https://github.com/1C-Company/GitConverter/blob/fcbb8f0656270a97793bd6795951d5b50df57add/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L2199

**Должно быть**
`Установка адреса Git-сервера выполнена с ошибкой`

**Comment by marmyshev** [comment]
Пул-реквест?
