### ISSUE TITLE
(1.0.7.3) Неверная проверка доступности платформы версии 8.3.15+

### ISSUE THREAD

**Issue by NikitaMikhaylovSB** [1C-Company/GitConverter#118]
https://github.com/1C-Company/GitConverter/blob/fcbb8f0656270a97793bd6795951d5b50df57add/GitConverter/src/Catalogs/%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B9/ObjectModule.bsl#L209

Данный код некорректный, т.к. при сверке платформы 8.3.15.х и 8.3.16.y - мы всегда будет получать ровно 1.
Поэтому должно быть изменено на:
`Возврат ОбщегоНазначенияКлиентСервер.СравнитьВерсии(ВерсияПлатформы, "8.3.15.0") > 0;`

Аналогично https://github.com/1C-Company/GitConverter/blob/fcbb8f0656270a97793bd6795951d5b50df57add/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L1111

https://github.com/1C-Company/GitConverter/blob/fcbb8f0656270a97793bd6795951d5b50df57add/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L2995

Ну и лучше вообще переделать на единый вызов, а не копипаст в разных местах

**Comment by NikitaMikhaylovSB** [comment]
+ обратная ситуация
https://github.com/1C-Company/GitConverter/blob/fcbb8f0656270a97793bd6795951d5b50df57add/GitConverter/src/Catalogs/%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B9/ObjectModule.bsl#L73

**Comment by NikitaMikhaylovSB** [comment]
И в расширении странно.

Тут правильно
https://github.com/1C-Company/GitConverter/blob/fcbb8f0656270a97793bd6795951d5b50df57add/GitConverter.%D0%9E%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B88315/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L18

и чуть ниже уже нет
https://github.com/1C-Company/GitConverter/blob/fcbb8f0656270a97793bd6795951d5b50df57add/GitConverter.%D0%9E%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B88315/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L24

**Comment by NikitaMikhaylovSB** [comment]
Что-то я логику перестал понимать (
https://github.com/1C-Company/GitConverter/blob/fcbb8f0656270a97793bd6795951d5b50df57add/GitConverter.%D0%9E%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B88315/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L63

**Comment by marmyshev** [comment]
> Что-то я логику перестал понимать (

В случае, если на сервере стоит версия 8.3.15 и НЕ выше - то тогда можно задействовать оптимизацию выгрузки, эта версия 8.3.15 установлена в настройках. Это ведь только для варианта когда сервер хранилищ на версии ниже чем 8.3.15
