### ISSUE TITLE
При инициализации репозитория ошибка

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/GitConverter#119]
**Описание ошибки**
При первой настройке выгрузки хранилища - ошибка инициализации репозитория

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть форму создания новой настройки
2. Нажать кнопку "Создать репозиторий"
3. Получим ошибку создания

`fatal: branch 'master' does not exist`

**Ожидаемое поведение**
Не должно быть ошибки инициализации

**Дополнительная информация**

Ошибка не блокирует дальнейшую работу!!! Просто можно продолжить...

Ошибка привнесена копипастом

https://github.com/1C-Company/GitConverter/blame/master/GitConverter/src/CommonModules/КонвертацияХранилища/Module.bsl#L2061

**Comment by marmyshev** [comment]
@NikitaMikhaylovSB спасибо за расследования!

**Comment by NikitaMikhaylovSB** [comment]
> @NikitaMikhaylovSB спасибо за расследования!
you are welcome
