### ISSUE TITLE
(1.0.7.3) Выгрузка только изменения на 8.3.16.1502 не происходит

### ISSUE THREAD

**Issue by NikitaMikhaylovSB** [1C-Company/GitConverter#124]
**Описание ошибки**
Для воспроизведения нужно обязательно сначала исправить #118 
На 8.3.16.1502 команда выгрузки изменений
`ДополнительныеПараметры = "-update -force -getChanges ""%ФайлИзменений%"" -configDumpInfoForChanges ""%ФайлСостоянияПредыдущейВерсии%""";`
работает не так, как ожидает конвертер. В частности: тут просто создается файл различий и не происходит выгрузки
Сейчас пришлось делать двойной проход (сначала типовой вызов, затем без флага getChanges для получения дампа файлов)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Исправить #118
2. Настроить выгрузку изменений платформой 8.3.16.1502
3. Выполнить выгрузку изменений
4. Убедиться, что будет произведена полная выгрузка вместо выгрузки изменений

**Ожидаемое поведение**
Осуществлять частичную выгрузку

**Comment by marmyshev** [comment]
@NikitaMikhaylovSB я вот обыскался в документации V8Update - ничего про изменения в поведении не нашел. В справке Конфигуратора - тоже никаких изменений.
Подскажи, на 8.3.15 ошибочное поведение не воспроизводится, а на 8.3.16 (и выше?) поведение ошибочное?

**Comment by marmyshev** [comment]
Да, только в дебаге понятно, что поведение изменилось.

**Comment by marmyshev** [comment]
9c3fe153e1c7118620b493a4640276f23701161f

**Comment by NikitaMikhaylovSB** [comment]
> @NikitaMikhaylovSB я вот обыскался в документации V8Update - ничего про изменения в поведении не нашел. В справке Конфигуратора - тоже никаких изменений.
> Подскажи, на 8.3.15 ошибочное поведение не воспроизводится, а на 8.3.16 (и выше?) поведение ошибочное?
Уже вижу, что воспроизвел )
Встречный вопрос: на платформу будет ошибка? В виде изменения поведения и/или отсутствия описания?

**Comment by marmyshev** [comment]
> Встречный вопрос: на платформу будет ошибка? 

Нет, не будет. Если более внимательно прочитать документацию к пакетным командам - там явно прописано какие команды работают в комбинации. То что на 8.3.15 неявно работал режим скобинированный из разных команд - это видимо недоработка. 

Будем считать - что сейчас корректное поведение на 8.3.16+
