### ISSUE TITLE
1.0.7.3: Отображение истории изменений в EDT при обновлениях (переименованиях) в конфигурации

### ISSUE THREAD

**Issue by NikitaMikhaylovSB** [1C-Company/GitConverter#125]
**Описание ошибки**
Обновляем ERP 2.5.3 на 2.5.5
При обновлении имя пакета XDTO EnterpriseData_1_7_5 меняется на EnterpriseData_1_7_8
Конвертер удаляет файлы, фиксирует коммит, добавляет новые файлы, фиксирует коммит.

В итоге мы теряем историю изменения объекта.

**Ожидаемое поведение**
Корректно проводить изменение файлов, без удаления-создания, как это делает EDT

**Comment by marmyshev** [comment]
В Конфигураторе обновление идет строго по UUID-ам и хранилище 1С объекты хранит оп UUID-ам. Если в одной версии удалили пакет и добавили ровно с таким же именем (даже не как в вашем примере с разными именами) но с другим UUID - то будет удаление и добавление нового объекта. Попробуйте проделать это в хранилище 1С - увидите ровно такую же ситуацию. 

поведение описано тут https://github.com/1C-Company/GitConverter/wiki/Как-это-работает#Коммит-в-git

**Comment by NikitaMikhaylovSB** [comment]
Поведение мне известно, это пример, когда просто переименовали объект и его история оказалась утерянной.

**Comment by marmyshev** [comment]
Уточните, UUID-ы у объектов метаданных EnterpriseData_1_7_5 и EnterpriseData_1_7_8 были одинаковые? Если да, то это может быть ошибка в гитконвертере.

**Comment by marmyshev** [comment]
Посмотрел сейчас историю - у нас этот объект корректно переименовывался ГитКонвретером начиная с 1.7.4 когда его добавили как новый, и до сегодняшнего дня.

![image](https://user-images.githubusercontent.com/4069973/97997306-e02c6480-1df9-11eb-85c0-29507975fe2f.png)

Есть возможность расследовать сейчас? есть командный файл по этой версии, файл логов?

**Comment by marmyshev** [comment]
UUID
![image](https://user-images.githubusercontent.com/4069973/97998417-1dddbd00-1dfb-11eb-8e29-1ca669b07072.png)

**Comment by NikitaMikhaylovSB** [comment]
Ага, я разобрался, где косяк.

Сам объект состоит из:
- папка EnterpriseData_1_7_8
-- файл EnterpriseData_1_7_8.mdo
-- файл Package.xdto

Так вот по файлам показывается полная история, а по папке - только с последнего переименования!
Когда я смотрю историю в навигаторе - EDT смотрит по папке и показывает мне обрезанную историю.
Т.е. файлы - ок, папка же новая, не переименовалась -> история потеряна.

![image](https://user-images.githubusercontent.com/37539066/98007851-eecc4900-1e04-11eb-83a8-f6d40fe9c2be.png)
![image](https://user-images.githubusercontent.com/37539066/98007858-f12ea300-1e04-11eb-91c4-902b3ac5079f.png)
![image](https://user-images.githubusercontent.com/37539066/98007862-f390fd00-1e04-11eb-8cee-5f0e117a8cb1.png)
![image](https://user-images.githubusercontent.com/37539066/98007869-f5f35700-1e04-11eb-93cf-30cedfbbf687.png)

**Comment by marmyshev** [comment]
Git отслеживает контент файлов, а папки - вещь виртуальная, видимо зависит от того как EGit/git создает представление папок в истории.
