### ISSUE TITLE
Зависает этап загрузки метаданных

### ISSUE THREAD

**Issue by yegor-novinsky** [1C-Company/GitConverter#127]
**Описание ошибки**
Зависает фоновая (регламентная) загрузка метаданных с EDT 2020.4.0+455. 
Java 

_openjdk version "11.0.6" 2020-01-15 LTS
OpenJDK Runtime Environment (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.6+10-LTS, mixed mode)_

Выполняемая строка
 
_ring edt workspace import  --workspace-location ""%РабочийКаталог%"" --configuration-files ""%КаталогФайловКонфигурации%"" --project ""%КаталогПроектаEDT%"" --version 8.3.15_

Дает предупреждение и зависает. Если прервать через часа два, то все вроде как нормально отрабатывает. Но как прерывать в регламентном(фоновом) задании, чтобы версия переходила на следующий этап?
Предупреждения такие

_Debug options:
    file:/C:/Program Files/1C/1CE/components/1c-edt-2020.4.0+455-x86_64/.options loaded
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.storage.FrameworkExtensionInstaller (file:/C:/Program%20Files/1C/1CE/components/1c-edt-2020.4.0+455-x86_64/plugins/org.eclipse.osgi_3.14.0.v20190517-1309.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.storage.FrameworkExtensionInstaller
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Warning: NLS unused message: Workbench_problemsRestartErrorTitle in: org.eclipse.ui.internal.messages
Warning: NLS unused message: Workbench_problemsRestartErrorMessage in: org.eclipse.ui.internal.messages
[WARN  ] config - Trusting all certificates configured for Client@7e7ac74d[provider=null,keyStore=null,trustStore=null]
[WARN  ] config - No Client EndPointIdentificationAlgorithm configured for Client@7e7ac74d[provider=null,keyStore=null,trustStore=null]_

Может, debug option как-то поправить?

Версия ГитКонвертера 1.0.7.3

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Установить на сервере 1С:Предприятие openjdk version "11.0.6" 2020-01-15 LTS
2. Установить EDT 2020.4.0+455
3. Настроить конвертацию Хранилища
4. Запустить конвертацию Хранилища

**Ожидаемое поведение**
Конфигурацию конвертируется в формат EDT

**Скриншоты, логи, ЖР**
Никаких скриншотов нет, в ЖР просто зачало фонового задания без его завершения

**Дополнительная информация**

Ситуация более или менее описана в https://partners.v8.1c.ru/forum/message/1937154

**Comment by marmyshev** [comment]
@yegor-novinsky можешь проверить еще раз на 2020.6?

У меня на 2002.4.0.449 не воспроизводится зависание... С ГитКонвертером это связано? Есть способ как это починить или обойти?

**Comment by yegor-novinsky** [comment]
Нет. С ГитКонвертером это никак не связано. Зависание в какой-то момент пропало само собой. Просто выдается указанная диагностика, которая мешает ГитКонвертеру прочитать нужную ему информацию.
