### ISSUE TITLE
Ошибка при нажатии на "ПроверитьДоступнуюВерсиюEDT"

### ISSUE THREAD

**Issue by BProg-Gladkov** [1C-Company/GitConverter#136]
Текст ошибки: Файл не обнаружен 'C:\Users\Гладков Антон\AppData\Local\Temp\3\v8_C367_e.txt'
Ошибка возникает если путь содержит пробелы. 

Необходимо исправление в общем модуле "КонвертацияХранилища" в функции "НеобходимоЗаполнитьВерсиюEDT"
Строка: СтрокаКоманды = "ring help modules > %ИмяФайлаВывода%";
Заменить на: СтрокаКоманды = "ring help modules > ""%ИмяФайлаВывода%""";

**Comment by BProg-Gladkov** [comment]
Аналогичная ошибка в функции ПолучитьСписокВерсийПлатформыEDT

**Comment by BProg-Gladkov** [comment]
Аналогичные ошибки возникают если путь к каталогу выгрузки версий содержит пробелы.

**Comment by marmyshev** [comment]
@BProg-Gladkov сделаешь пул-реквест с исправлением?

**Comment by BProg-Gladkov** [comment]
Добрый день.c Git только начал работать. Постараюсь сегодня сделать. 09.11.2020, 15:53, "Dmitriy Marmyshev" <notifications@github.com>: @BProg-Gladkov сделаешь пул-реквест с исправлением?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
