### ISSUE TITLE
Коллеги, кто сможет помочь запустить этого зверя ?

### ISSUE THREAD

**Issue by Yamaliev-Azat** [1C-Company/GitConverter#153]
azat_y@mail.ru

**Comment by LazarenkoA** [comment]
Если для тебя сложен этот зверь, поищи другие альтернативы, благо они есть.

**Comment by marmyshev** [comment]
Ну еще всегда остается путь - почитать документацию https://github.com/1C-Company/GitConverter/wiki  или спросить в офциальном телеграмм-чате https://t.me/e1c_edt

**Comment by marmyshev** [comment]
Если есть конкретные вопросы или непонятки с документацией - тоже пиши...

**Comment by bopoh13** [comment]
Для работы требуется [1С:Enterprise Development Tools](https://edt.1c.ru/docs/new/download.php). Серия видео по настройке **GitConverter**: https://www.youtube.com/watch?v=0Y8Zy2bdCEk&list=PLVUuD_WTdwSLTW4TSKf7IoMjG2_mqP64h
