### ISSUE TITLE
После конвертации не удаляются записи из списка инфобаз

### ISSUE THREAD

**Issue by VladFrost** [1C-Company/GitConverter#17]
Это запланированное поведение?
![2018-02-26 14_55_16](https://user-images.githubusercontent.com/11960251/36669225-3c1dbfd2-1b05-11e8-8ea5-4461ae166983.png)

**Comment by marmyshev** [comment]
Возможности удалять из списка стандартными средствами Платформы нет. К сожалению это можно только обходить: например настроить регулярное удаление файла списка или запустить ГитКонвертер от имени другого пользователя в системе (если используется одна машина совместно с человеком).

Нужно не забывать, что еще необходимо чистить файлы кэша ИБ. Например такой `*.bat` файл можно запускать с помощью Планировщика Windows:

```cmd
@REM "Удаление старых каталогов за 5 дней"
forfiles /p "c:\Users\Администратор\AppData\Roaming\1C\1cv8" /S /D -5 /C "cmd /c IF @isdir == TRUE rd /S /Q @path"
forfiles /p "c:\Users\Администратор\AppData\Local\1C\1cv8" /S /D -5 /C "cmd /c IF @isdir == TRUE rd /S /Q @path"
```

**Comment by nixel2007** [comment]
А зачем вообще базы добавляются в список инфобаз?

**Comment by pumbaEO** [comment]
Насколько я помню, если базу добавили в список, но при этом в коммандном режиме указываем  путь подключения к базе как `/Fc:\mypath` тогда все равно используется кэш нулевой, т.е. папочка 0000-0000-00000-00000000. Что-бы уже использовался именно кеш базы, тогда надо указывать строку подключения как имя в списке баз `/IBName ...` тогда будет честное использование кэша именно той временной базы.

**Comment by marmyshev** [comment]
> Что-бы уже использовался именно кеш базы, тогда надо указывать строку подключения как имя в списке баз /IBName ... тогда будет честное использование кэша именно той временной базы.

Это не верно, кэш метаданных используется если в `списке баз` есть база с указанным **путем**. `/IBName ...` влияет только на поиск базы для запуска.

> А зачем вообще базы добавляются в список инфобаз?

кэш метаданных влияет на скорость выполнения пакетных операций `Конфигуратора`. Для таких конфигураций как  1C:ERP скорость очень важна.
