### ISSUE TITLE
Прошу отключить обязательное заполнение полей `Пользователь` и `Пароль`

### ISSUE THREAD

**Issue by VladFrost** [1C-Company/GitConverter#19]
Сейчас в форме элемента справочника `ХранилищаКонфигураций` установлен признак обязательного заполнения для полей `Пользователь` и `Пароль`. При использовании авторизации по ssh-ключу, эти поля не требуются.
![2018-03-15 12_11_07](https://user-images.githubusercontent.com/11960251/37454055-938cd09e-284a-11e8-96da-f7b576d92070.png)

**Comment by marmyshev** [comment]
Ок, согласен, надо доделать.

Пока временно можно обойти так:
в **Адрес репозитория git** вписать любое значение. В **Пользователь** и **Пароль** добавить любые символы и **НЕ** нажимать кнопку добавления адреса сервера в настройки.

Вручную в командной строке добавить `git remote add ...` нужный сервер по ssh.

**Comment by pumbaEO** [comment]
Напомню, что пароль и пользователя можно не указывать не только при способе авторизации по ssh ключу, но и можно установить https://github.com/Microsoft/Git-Credential-Manager-for-Windows. 

т.е. не обязательно добавлять какое-то перечисления типа "тип аутентификации" и по этому проверять заполненность полей Пользователь и Пароль.

**Comment by marmyshev** [comment]
Доделать вмест с #10

**Comment by JohnyDeath** [comment]
> но и можно установить https://github.com/Microsoft/Git-Credential-Manager-for-Windows

более того, теперь эта утилита идет в стандартном инсталяторе git-а для windows

**Comment by marmyshev** [comment]
Пока (как способ) обхода добавил инфу по авторизации в вики [https://github.com/1C-Company/GitConverter/wiki/Авторизация-в-сервере-Git](https://github.com/1C-Company/GitConverter/wiki/Авторизация-в-сервере-Git)
