### ISSUE TITLE
Вопрос по правильной настройке хранилища

### ISSUE THREAD

**Issue by KrivickyA** [1C-Company/GitConverter#22]
Доброго времени суток!

Хотелось попробовать сконвертировать конфигурацию в формат EDT. Для теста развернул локальную базу GitConverter и столкнулся с неожиданной проблемой.
В описании указано, что для начала разбора нужно заполнить константу "Путь к версиям платформы на сервере". Т.к. для проверки выполняю все операции в тестовом режиме с локальной файловой базе, то и путь указал к локальному каталогу, где у меня установлены все версии платформы: "D:\Program".
При попытке запустить разбор данных, система падает с ошибкой на этапе попытки создания локальной файловой базы. Место ошибки и входные параметры на скриншоте:
![2018-03-23_13h04_40](https://user-images.githubusercontent.com/23094215/37824308-3676bb14-2e9d-11e8-9cb5-3aa7fbbf0f49.png)
Выполняется попытка выполнить строку:
`ЗапуститьПриложение(СтрокаКоманды, Параметры.КаталогИсполняемогоФайла, Истина, КодВозврата);`
При этом путь к исполняемому файлу не достроен корректно. 
К общему каталогу установленных платформ "D:\Program"  добавлен подкаталог "1cv8" и все, на этом сборка пути окончена. Хотя я ожидал, что будет собран полный путь к исполняемому файлу, с учетом указанной в настройках хранилища версии платформы.
Т.е. должен был получиться вот такой путь:
"D:\Program\1cv8\8.3.10.2252\bin\1cv8.exe".
И как следствие получаю ошибку вида: 
![2018-03-23_13h10_33](https://user-images.githubusercontent.com/23094215/37824643-55ebe388-2e9e-11e8-90bc-d1eb5e311962.png)

Подскажите. возможно я что-то упустил и  настроил неверно? 
Но судя по коду я не нашел использования версии платформы при построении пути к исполняемому файлу.. да и собственно этот путь никак не строится.

**Comment by KrivickyA** [comment]
Похоже с проблемой разобрался... 
В описании Wiki у Вас не по алгоритму заполнения константы "Путь к версиям платформы на сервере" нет какой либо детальной информации.
Абсолютно случайно ушел по ссылке на ИТС и там обнаружился нужный мне абзац:
`**Настройка базы ГитКонвертера**

1. Разместите базу ГитКонвертера на сервере "1С:Предприятия". Работа в файловом режиме может быть использована только в демонстрационных целях.

2. **Заполните константу "Путь к версиям платформы на сервере", где располагаются файлы Конфигуратора 1cv8(.exe) в формате: C:\Program files (x86)\1cv8\%ВерсияПлатформы%\bin , где в параметр %ВерсияПлатформы% - будет подставлена текущая версия хранилища из настроек.**

3.  Для ограничения производительности можно включить константу "Использовать очереди выполнения" - количеством очередей можно балансировать нагрузку на сервер.`

Добавьте пожалуйста этот комментарий в ReadMe и вики.

**Comment by marmyshev** [comment]
Вики в проекте не нашел :( 
ИТС и ReadMe на гитхабе - совпадают https://github.com/1C-Company/GitConverter#Настройка-базы-ГитКонвертера (это один и тот же проект)

а еще можно было посмотреть в подсказке при заполнении константы... но настоящие программисты подсказок не читают! :)
