### ISSUE TITLE
Не учитываются ошибки с окончаниями строк в хранилище

### ISSUE THREAD

**Issue by svcoder1980** [1C-Company/GitConverter#28]
Проблемы две: 
1. CR без LF. Файлы с такой ошибкой не попадают в индекс
2. LF без CR. При рекомендуемых настройках возникает ошибка "fatal: LF would be replaced by CRLF"
Я после каждого получения данных из хранилища запускать скрипты на Python которые это фиксят

**Comment by marmyshev** [comment]
В версии 1.0.5 эту проблему сделал менее значимой: в настройки добавляются **core.safecrlf=warn** 
Рекомендации (описанные в ридми **core.safecrlf=true** ) взяты из документации к EDT. Эта настройка полезна при разработке- когда ты сам редактируешь файлы - гит сообщает о проблеме, которую нужно исправлять (вручную). Но настройка **=true** оказалась бесполезна когда конвертируем историю версий, где мы ничего уже поменять не можем.

**Comment by svcoder1980** [comment]
Спорное решение, т.к. в определенный момент появится необходимость конвертировать хранилище в формат EDT, а там уже нужно правильное помещение окончаний строк.

**Comment by pumbaEO** [comment]
Очень, очень странно использование ```git config core.autocrlf true ``` без использования .gitattributes . 1С при выгрузки в исходники принудительно всегда выгружает модули с окончанием строк "CRLF", без разницы это в Windows или же в linux.

**Comment by marmyshev** [comment]
> Спорное решение, т.к. в определенный момент появится необходимость конвертировать хранилище в формат EDT

В чем спорность?
Это добавлено в 1.0.5 - а в этой версии уже по умолчанию конвертируется в формат EDT. (см. ветку develop)

**Comment by svcoder1980** [comment]
То есть вы полагаетесь на то, что не важно как окончание строки LF попало в Git, преобразованием из CRLF или через помещение LF?

**Comment by leemuar** [comment]
Не понимаю необходимости autocrlf = true

Это настройкой изменяются содержимое справки, прав доступа, макетов и другие объекты. Зачем это нужно? Не лучше ли оставлять как есть, как выгрузила сама платформа?

```
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеУстановкиБлокировокЯчеек/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеФизическихЛиц/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеФинансовыхРезультатов/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеЦенНоменклатуры/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеЦенНоменклатурыСОграничением/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеЦенПартнеров/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеЧековККМ/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеШаблоновСообщений/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Roles/ЧтениеЭД/Rights.rights.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/SettingsStorages/ХранилищеВариантовОтчетов/Forms/ВыборВариантаОтчета/Help/ru.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/SettingsStorages/ХранилищеВариантовОтчетов/Forms/СохранениеВариантаОтчета/Help/ru.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in ut_rf/src/Subsystems/Администрирование/Help/ru.html.

```

**Comment by marmyshev** [comment]
> Не понимаю необходимости autocrlf = true

@leemuar почитайте документацию EDT

**Comment by leemuar** [comment]
@marmyshev подскажите какой именно раздел? Видимо я пропустил это

**Comment by marmyshev** [comment]
Из документации в EDT: Руководство разработчика -> Сценарии работы -> Групповая разработка -> Настройка Git для совместной работы

**Comment by leemuar** [comment]
@marmyshev Почитал. Там написано "Если ... используют разные операционные системы", я так понимаю ключевое слово тут именно "Если", это не требование, а рекомендация при наличии необходимости. А Конвертер ставит эту настройку сам по умолчанию.

Я еще не проверял как выгружает тот же проект EDT на linux, но судя по комментарию @pumbaEO:

> 1С при выгрузки в исходники принудительно всегда выгружает модули с окончанием строк "CRLF", без разницы это в Windows или же в linux.

По комментариям других людей в этом ишузе они тоже считают безусловность этой настройки вредной для себя.

Предлагаю вынести это в настройки выгрузки хранилища. Чтобы те кому надо - могли отключить для себя

П.С. А почему закрыли ишуз? Он вроде висел как открытый для обсуджения?

**Comment by marmyshev** [comment]
1С:Предприятие - поддерживает работу на разных операционных системам, 1C:EDT - тоже поддерживает редактирование завязанное на разделитель ОС (или проекта, если не по умолчанию). Поэтому 1С:ГитКонвертер по умолчанию поддерживает такое поведение. 

В общем случае, у вас нет ограничений менять любые параметры настройки Git-репозитория `на свой страх и риск` - главное чтобы вы понимали зачем это делаете.

**Comment by pumbaEO** [comment]
Имхо, для разных ОС, настройка autocrlf = true полезна, единственно, что для 1С надо не забівать настроить правильно служебный файл .gitattributes где и прописать необходиміе окончания строк для файлов bsl, xml, при этом современные внешние редакторы читают настройки из этого файла и автоматом применяют окончания строк к совпадающему по маске.

**Comment by marmyshev** [comment]
> для 1С надо не забівать настроить правильно служебный файл .gitattributes где и прописать необходиміе окончания строк для файлов bsl, xml

Ну если ГитКонвертер используется не по назначению - т.е. не для перехода в 1C:EDT, а для использования в других редакторах - то опять же, "нет ограничений настраивать .gitattributes" как угодно перед началом конвертации. Но для проектов 1C:EDT это не нужно - т.к. checkout для всех текстовых типов файлов нужно выполнять с настройками ОС.
