### ISSUE TITLE
Не хватает версии конфигурации в комментарии коммита

### ISSUE THREAD

**Issue by svcoder1980** [1C-Company/GitConverter#29]
При просмотре истории изменений в файле в каком-нибудь Git-клиенте не хватает версии конфигурации в которой было выполнено то или иное изменение
Брать ее придется видимо из Configuration.xml

**Comment by marmyshev** [comment]
К сожалению в отчете по версиям хранилища нет информации о версии. Ее действительно нужно брать из **Configuration.xml**. Можете написать 1С-расширение которое будет на этапе «Загрузки метаданных» или сразу после «Выгрузки версии» зачитывать версию из файла (учитывайте только выгрузку изменений в которой может не быть файла Configuration.xml) и добавляйте к полю Комментарий в версии.

**Comment by marmyshev** [comment]
Или чтобы не «портить» оригинальный комментарий - сохраняйте в файл **version.txt** в каталог временных файлов версии, а на этапе формирования файла комментария для гита - добавляйте эту версию...
Рекомендую сразу взять версию 1.0.5 из ветки develop

**Comment by svcoder1980** [comment]
Какой смысл добавлять файл version.txt если ту же функции выполняет файл Configuration.xml?

**Comment by nixel2007** [comment]
Ещё можно вешать новый тег при первом/последнем появлении версии. Так и комментарии не портятся и информация сохраняется

**Comment by marmyshev** [comment]
> Какой смысл добавлять файл version.txt если ту же функции выполняет файл Configuration.xml?

Ну так ведь вопрос ваш был "Не хватает версии конфигурации в комментарии" а не в файлах.
Я предлагал вам добавлять инфу из version.txt в файл комментария при формировании файла комментария, но можете сразу считывать из Configuration.xml... :) как вам угодно :)

**Comment by marmyshev** [comment]
> Ещё можно вешать новый тег при первом/последнем появлении версии. Так и комментарии не портятся и информация сохраняется

@nixel2007 можно. Готовы сделать это расширением? Кажется будет удобная полезная фича...
