### ISSUE TITLE
Проект не импортируется в EDT

### ISSUE THREAD

**Issue by Stepa86** [1C-Company/GitConverter#3]
При попытке импортировать проект согласно примерам с ИТС https://its.1c.ru/db/edt16doc#content:267:hdoc  проект не определяется, как 1Сный.

Возможно это связано с отсутствием файла GitConverter/.project и с его игнорированием. После добавления этого файла проект был успешно импортирован и запущен.

**Comment by marmyshev** [comment]
Да, спасибо, поправил. Сорри, не увидел ваш риквест.
