### ISSUE TITLE
Использование очередей выполнения не выполняет коммиты

### ISSUE THREAD

**Issue by svcoder1980** [1C-Company/GitConverter#33]
На самом деле вопрос даже шире. Какие должны быть настройки для инкрементного обновления репозитария Git и установленном флаге "Использовать очереди выполнения"? По идее фоновое задание конвертации нужно запускать только для запуска процесса и далее при появлении новых версий в хранилище 1С. По факту без постоянного запуска задания конвертации не получаются новые версии и не выполняются коммиты.

**Comment by svcoder1980** [comment]
@marmyshev 
2. Но это регламентное задание при каждом запуске также создает временную ИБ и получает отчет о новых версиях, что лишнее, когда выполняется конвертация истории хранилища

**Comment by marmyshev** [comment]
См. https://github.com/1C-Company/GitConverter/wiki/Параметры-конвертации
> Если указана версия окончания - не будет выполняться запрос новых версий.

Есть мысль описать различные сценарии использования ГитКонвертера и оптимальные настройки к ним.

**Comment by svcoder1980** [comment]
Если указать версию окончания - не будет работать получение из хранилища новых версий. Текущая реализация не позволяет настроить GitConverter для оптимальной синхронизации хранилища Git по данным хранилища 1С

**Comment by marmyshev** [comment]
> Текущая реализация не позволяет настроить GitConverter для оптимальной синхронизации хранилища Git по данным хранилища 1С

Почему не позволяет? И что есть "оптимальность синхронизации" (или неоптимальность) по вашему мнению? Опишите весь сценарий применения ГитКонвертера.

**Comment by svcoder1980** [comment]
Оптимальная синхронизация означает, что не нужно настраивать регламентное задание, которое постоянно создает тестовую базу для получения новых версий. Желаемый сценарий я описал в самом начале.
1. Регламентное задание хранилища конфигурации настраивается с учетом желаемой оперативности синхронизации с хранилищем Git. Например раз в сутки. Единственное что оно делает - дополняет справочник ВерсииХранилища новыми версиями
2. Новая операция очереди выполнения нужна, чтобы выполнить коммиты и создать новые ИБ для версий (периодичность выполнения раз в 10 минут)
3. Операции - Выгрузка конфигурации и Загрузка метаданных остаются без изменений (периодичность выполнения раз в 10 минут)
