### ISSUE TITLE
Не работает выгрузка изменений на версии платформы 8.3.10

### ISSUE THREAD

**Issue by svcoder1980** [1C-Company/GitConverter#34]
В общем на платформе 8.3.10.2753 следующий командный файл не проверяет наличие изменений, а тупо выгружает все. На 8.3.11.3034 такой проблемы нет, поэтому можно смело повышать требование к платформе для опции "Выгружать изменения":
DESIGNER /DisableStartupDialogs
  /F "d:\base\15\db\"
 
 
 /DumpConfigToFiles "d:\base\15\dump\" -update -force -getChanges "d:\base\15\diff.txt" -configDumpInfoForChanges "d:\base\15\PreviousState.xml"
 /DumpResult "d:\base\15\result.txt"
 /Out "d:\base\15\log.txt" -NoTruncate

**Comment by marmyshev** [comment]
а что в файле "d:\base\15\diff.txt" написано? 
Выгрузка изменений может быть не всегда а только когда это возможно (см. документацию) - вы ведь проверяли 8.3.10 и 8.3.11 на одной и той же версии - на №15? или на разных версиях хранилища?

**Comment by svcoder1980** [comment]
fulldump
Да, я использовал тот же командный файл, что сформировался для версии 8.3.10 и в там был небольшой список объектов

**Comment by marmyshev** [comment]
`fulldump` - означает, что невозможно выгрузить изменения. Если на одной и той же базе на разных версиях платформы (8.3.10 и 8.3.11) выдается разный результат в файл diff
- 8.3.10 - `fulldump`
- 8.3.11 - много строк с измененями

то это похоже на ошибку Платформы - зарегистрируйте ошибку через канал поддержки платформы.

**Comment by svcoder1980** [comment]
Вы же понимаете, что 1С не будет выпускать исправительную версию для 8.3.10. Я поэтому и написал, что выгрузка изменений на 8.3.10 работать не будет и следует написать об этом в описании. Я проверил 15 версий хранилища на 8.3.10 и все они выгрузились с опцией fulldump.

**Comment by marmyshev** [comment]
> Вы же понимаете, что 1С не будет выпускать исправительную версию для 8.3.10

https://releases.1c.ru/project/Platform83 - 1С до сих пор выпускает исправительные версии для 8.3.10. Зарегистрировать надо :)

**Comment by svcoder1980** [comment]
Имея опыт общения с 1С - 99.99% ответят что ошибка исправлена в 8.3.11
