### ISSUE TITLE
Если путь к хранилищу больше 120 символов, то на PostgreSQL не запускается задание конвертации.

### ISSUE THREAD

**Issue by Oxotka** [1C-Company/GitConverter#36]
Если путь к хранилищу больше 120 символов, то на PostgreSQL не запускается задание конвертации.
Длинное название может быть из-за расположения хранилища в сети.

Проблема в том, что длина имени задания в PostgreSQL ограничена. И при попытке создать задание - ошибка.

Решили проблему таким образом:
1. В Модуле объекта справочника "ХранилищаКонфигурации" в процедуре "ПередЗаписью" заменили строку https://github.com/1C-Company/GitConverter/blob/21fcba3ad573a0d6476ede0110d7ce14a2fc2fa1/GitConverter/src/Catalogs/%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B9/ObjectModule.bsl#L29
на:

`ПараметрыЗадания.Вставить("Наименование", НСтр("ru = 'Конвертация хранилища'") + ": " + СокрЛП(Прав(Адрес, 100)));`

2. В Модуле объекта справочника "ХранилищаКонфигурации" в процедуре "ПриЗаписи" заменили строку 
https://github.com/1C-Company/GitConverter/blob/21fcba3ad573a0d6476ede0110d7ce14a2fc2fa1/GitConverter/src/Catalogs/%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B9/ObjectModule.bsl#L93
на:

`НаименованиеЗадания = НаименованиеЗадания + СокрЛП(Прав(Адрес, 100));`

**Comment by Oxotka** [comment]
В нашем случае такое исправление может не помочь.
Потому что левая часть хранилищ одинаковая - это путь к хранилищу в сети. 
Содержательная и различающаяся часть имени хранилища находится как раз в конце. 
А здесь она может быть обрезана.

**Comment by marmyshev** [comment]
@Oxotka а для чего вам в наименовании ФЗ нужно отличать друг от друга?
В чем должно было помочь исправление (кроме возможности запуска на PostgreSQL)?

**Comment by Oxotka** [comment]
Да, наверно, не нужно отличать.
Я просто переживал, что если будет два одинаковых наименования, то что-то может пойти не так. Но эти опасения ничем не обоснованы.
