### ISSUE TITLE
Выгрузка оригинальной и конвертированной в EDT версии в параллельные ветки

### ISSUE THREAD

**Issue by VladFrost** [1C-Company/GitConverter#40]
Хочется иметь параллельную выгрузку в git оригинальной и конвертированной в EDT версии в две разные ветки.

**Comment by marmyshev** [comment]
Под "оригинальной" имеется ввиду формат xml 1С:Предприятия?

Если да, то зачем 2 несовместимых формата в одном репозитории? у веток должен быть "общий предок" - но его идеологически не существует...

Что мешает конвертировать просто в 2 отдельных репозитория параллельно? один в xml, другой в EDT...

Что мешает сейчас создать ветку оригинальную (или) ветку EDT в одном репозитории и конвертировать в них параллельно?

**Comment by VladFrost** [comment]
Действительно, ничего не мешает, можно конвертировать параллельно.
