### ISSUE TITLE
При ошибке коммита операция все равно считается успешной и версия помечается как успешно помещенная

### ISSUE THREAD

**Issue by leemuar** [1C-Company/GitConverter#46]
Если коммит в репозиторий завершится ошибкой (не будет выполнен, команда вернет результат, отличный от 0) - конвертер все равно посчитает версию успешно выгруженной, коммит успешно выполненным и перейдет к выгрузке следующей версии. Хотя коммитов в репозитории git не будет вообще

Как воспроизвести: 
1. На системах Windows
2. Убедиться, что core.longpaths отключен (равен false)
3. Поместить в хранилище объект конфигурации с очень длинным именем
4. Запустить выгрузку в конвертере

У меня коммит падал с ошибкой "filename is too long", полный путь к файлу был примерно 320 символов

**Comment by marmyshev** [comment]
@leemuar уточни, в лог версии добавляется такая строка?

`.... Окончание коммита в Git. Код возврата: 1`
