### ISSUE TITLE
Ошибка удаления файлов проекта EDT в версии останавливает конвертацию

### ISSUE THREAD

**Issue by leemuar** [1C-Company/GitConverter#47]
Словили такую ошибку при конвертации хранилища:

![image](https://user-images.githubusercontent.com/5869791/46939521-270e5c80-d06f-11e8-93e0-7082a9451825.png)

![image](https://user-images.githubusercontent.com/5869791/46942192-7061aa80-d075-11e8-9881-f038fb8cb674.png)

Возможно вызвано длинными именами в путях. Насколько я понял это происходит при очистке каталогов с временными файлами. Проблема в том, что при ошибке удаления конвертация дальше не работает, застревает на той версии, удалить файлы которой не получается

Возможно стоит сделать так, чтобы ошибка удаления временных файлов не приводила к остановке выгрузки, просто игнорировалась

**Comment by VladFrost** [comment]
Здесь можно, например, отключить флажок "Удалять временные файлы после коммита". + в качестве каталога выгрузки версий использовать максимально короткое имя. Не `c:\temp\gitconverter` как у вас, а, например `c:\g`

**Comment by nixel2007** [comment]
longpaths в true не поможет?

**Comment by leemuar** [comment]
@VladFrost как обходное решение - да, пойдет. Но хотелось бы доработать так, чтобы такие ошибки не останавливали конвертацию

@nixel2007 скорее всего не поможет, т.к. это не ошибка git. Это ошибка удаления файлов на диске функцией 1С УдалитьФайлы()

**Comment by pumbaEO** [comment]
Слишком длинное полный путь к каталогу. Переносим все c:\a, c:\b, c:\c каталоги и надемся, что поможет. Если не помогает, то надо удалять файлы правильно, т.е. делать текущим каталогом МоеДлинноеИмя и там удалять только 1 файл.

**Comment by leemuar** [comment]
@VladFrost видимо отключение флажка "Удалять временные файлы после коммита" не поможет. Ошибка тут:

https://github.com/1C-Company/GitConverter/blob/master/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L1421-L1428

тут флажок "Удалять временные файлы после коммита" ни на что не влияет, удаление безусловное

**Comment by leemuar** [comment]
![image](https://user-images.githubusercontent.com/5869791/46951664-51711180-d091-11e8-9476-b0ba583d5edd.png)

**Comment by marmyshev** [comment]
Тут никуда не деться - при такой ошибке - надо останавливать конвертацию.

А в документации к 1С - есть требование на длину имен объектов Конфигурации и общего пути для выгрузки.

К сожалению тут ничего нельзя сделать для исторических версий в Хранилище, кроме как обновиться на Windows 10, 2016 и отключить ограничение на длину путей, а так же максимально сократить длину путей для конвертации (расположение гит-репы, и выгрузок версий)

**Comment by leemuar** [comment]
@marmyshev поясните, пожалуйста, почему "при такой ошибке - надо останавливать конвертацию"? Для меня выглядит так, что такие ошибки можно игнорировать - это же просто очистка временных файлов. Я не правильно понял алгоритм выгрузки?

**Comment by marmyshev** [comment]
Не правильно понимаете алгоритм: тут ошибка удаления каталога в который конвертируется проект в формате EDT, невозможность удаления этих файлов приводит к ошибке конвертации EDT по аналогичной причине - длинна пути. Проблему длинных путей надо решать в ОС а не в ГитКонвертере.

Про процесс конвертации можно почитать тут: https://edt.1c.ru/upload/docs_git/EDT&GIT.html глава 6 п.4
