### ISSUE TITLE
Не все *.bin являютса бинарными данными.

### ISSUE THREAD

**Issue by pumbaEO** [1C-Company/GitConverter#5]
В документации написано, что файлы по маске *.bin являютса бинарными, но это не так. Файлы `XDTOPackages/*/Ext/Package.bin` являютса текстовыми, хоть и имеют ошибочное расширение bin.

**Comment by marmyshev** [comment]
Да, верно подмечено.
Аналогинчо, в макет с "Двоичными данными" можно добавить текстовый файл или xml - формально данные текстовые, но Платформой считаются как "двоичные" - расширение будет тоже `".bin"`.  

В текущем примере можно применить более детальный фильтр:

```bash
git lfs track "*/Ext/Template.bin"
git lfs track "*/Ext/Module.bin"
```

LFS можно вообще не использовать - это рекомендация. Имхо, есть смысл использовать на оч больших конфигурациях с большой историей.

Анализировать историю xml-файлов в текстовом представлении - вообще очень не просто :)
