### ISSUE TITLE
[ERROR] Ошибка при создании объекта c IID

### ISSUE THREAD

**Issue by leemuar** [1C-Company/GitConverter#51]
Словили такую ошибку при выгрузке ~200й версии из хранилища:

![image](https://user-images.githubusercontent.com/5869791/47003396-d0b92080-d137-11e8-9f5d-4e9761130bba.png)

в журнале регистрации записи на 2 строки кода:

![image](https://user-images.githubusercontent.com/5869791/47003523-1544bc00-d138-11e8-9e62-19d08f163a32.png)

https://github.com/1C-Company/GitConverter/blob/c482b38/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L2513

https://github.com/1C-Company/GitConverter/blob/c482b38/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L2596

в log.txt:
```
10/16/2018 8:39:34 AM Начало создания базы.
Создание информационной базы ("File="C:\g\report_db\";Locale = "en_US";") успешно завершено
10/16/2018 8:39:35 AM Окончание создания базы.
Код возврата: 0, Код результата: 0
10/16/2018 8:39:35 AM Начало формирования отчета по хранилищу.
Ошибка при создании объекта c IID - 332c4425-26cb-11d0-b483-00c04fd90119
[helpui - src\helpmiscUI.cpp (636)]
10/16/2018 8:39:36 AM Окончание формирования отчета по хранилищу.
Код возврата: 1, Код результата: 0
```
Что это такое? Из-за чего может происходить?

**Comment by marmyshev** [comment]
Конфигуратор не может сформировать отчет. Может в момент соединения с хранилищем произошла сетевая ошибка, или физически БД хранилища может быть повреждена.


Попробуйте зайти в пустую базу, открыть там хранилище и сформировать отчет начиная с версии которая была загружена в ГитКонвертер - это проверка. Но этот отчет еще можно вручную загрузить в ГитКонвертер (кнопка в форме настроек хранилища)

**Comment by leemuar** [comment]
У нас периодически по неизвестным причинам "слетает" подключение к хранилищам с ошибкой "Соединение с хранилищем не установлено". Возможно тут то же самое. В данном случае странно, т.к. сервер хранилища и каталог выгрузок установлены физически на одной машине.
Пока продолжаем искать причину проблемы.

**Comment by leemuar** [comment]
Теперь эта ошибка воспроизводится всегда, перестали конвертироваться все хранилища.
Создаю новую конвертацию - ошибка повторяется.

Попробовали выполнить команду создания отчета вручную в командной строке - получили странную ошибку "Каталог не обнаружен":

![image](https://user-images.githubusercontent.com/5869791/47290337-97852280-d607-11e8-8c58-03082ae2c9b4.png)

**Comment by leemuar** [comment]
Теперь перестали работать конвертации всех хранилищ, все выдают эту ошибку.
Пробовал подключаться к хранилищу из конфигуратора - все нормально.

Создание новой конвертации  не помогает, перенос временных каталогов на другой диск не помогает.

**Comment by marmyshev** [comment]
А вручную база создается, подключается, отчет формируется? 

Можете попробовать выполнить команду 
`"C:\Program files\1cv8\<версия>\bin\1cv8 /@ "C:\path_to_dumps\params_e99e4de3-a470-11e8-8104-0050569f237c_00000000-0000-0000-0000-000000000000_1.txt"` в которой замените имена файлов на свои - это будет пакетная команда которую выполняет ГитКонвертер для получения отчета по хранилищу. У вас она выполняется? Если нет, то что пишет в лог? Если то же самое - то проблема явно не с ГитКонвертером...

**Comment by leemuar** [comment]
@marmyshev вручную база создается, из конфигуратора к хранилищу подключается, отчет формируется.

Выполнил команду формирования отчета вручную в консоли - отчет сформировался успешно, без ошибок. Пробовал вместо подключения к серверу хранилища указать каталог хранилища - получаю ту же ошибку.

Никак не могу понять как определить источник проблемы. Вручную все работает нормально, а запуск из Конвертера выдает ошибку

**Comment by leemuar** [comment]
Есть подозрение, что данная ошибка вызвана повреждением хранилища

**Comment by VladFrost** [comment]
> Физически перезагрузили сервер - ошибка пропала

У меня, кстати, тоже такая ошибка периодически вылезает. Помогает перезагрузка сервера. Но это как-то неправильно.

**Comment by DimaBrn** [comment]
Завел тему на партнерском форуме https://partners.v8.1c.ru/forum/topic/1793538

**Comment by pantifeek** [comment]
Решение найдено? ГитКонвертер работает 1-2 дня, потом начинается ошибка:
```
03.06.2019 13:55:40 Начало формирования отчета по хранилищу.
Ошибка при создании объекта c IID - 332c4425-26cb-11d0-b483-00c04fd90119
[helpui - src\helpmiscUI.cpp (636)]
03.06.2019 13:55:44 Окончание формирования отчета по хранилищу.
Код возврата: 1, Код результата: 0
```

**Comment by DimaBrn** [comment]
читаем issue #91
