### ISSUE TITLE
Как собирать проекты из формата выгрузки EDT?

### ISSUE THREAD

**Issue by leemuar** [1C-Company/GitConverter#52]
Допустим мы разрабатываем на EDT и храним код в git.
Как нам автоматизировать сборку конфигурации из формата EDT? Какие инструменты и команды нужны?

При использовании выгрузки в файлы понятно как - у конфигуратора есть команда /LoadConfigFiles. Но формат хранения EDT же вроде другой? Как из этого формата собирать конфигурации на CI/CD серверах? Что использовать и где про это почитать подробнее?

**Comment by marmyshev** [comment]
Вопрос конечно тянет на отправку в форум поддержки EDT... :)

Но посмотрите документацию к EDT + ring

1. `ring edt workspace export ...` - экспорт в формат xml платформы
2. `1cv8 CREATEINFOBASE ...` - создаете пустую базу
3. `1cv8 DESIGNER ... /LoadConfigFromFiles ...` - загружаете в базу из xml
4. `1cv8 DESIGNER ... /CreateDistributionFile ...` - создание поставки

**Comment by hawk911** [comment]
@leemuar [тут](https://infostart.ru/public/838136/) для CI, да и в целом понятен синтаксис.

**Comment by marmyshev** [comment]
Только не делайте такую же "глупость" ;) как описано в статье - 4 джоба на задачу "создать cf" - ведь эти джобы все будут выполняться параллельно (одновременно), + еще проблема как передавать тысячи файлов xml между джобами...
