### ISSUE TITLE
При записи элемента "ХранилищаКонфигураций" cбрасывается флаг "ВыгружатьИзменения" если не заполнен реквизит "ВерсияПлатформы"

### ISSUE THREAD

**Issue by VladFrost** [1C-Company/GitConverter#54]
Для обхода ошибки нужно заполнить поле `ВерсияПлатформы`
https://github.com/1C-Company/GitConverter/blob/master/GitConverter/src/Catalogs/ХранилищаКонфигураций/ObjectModule.bsl#L50

**Comment by leemuar** [comment]
Тоже на это наткнулся, только с причинами не разобрался.
Наверно хотелось бы, чтобы система явно сообщала что необходимо сделать для использования очередей, какое поле заполнить

**Comment by marmyshev** [comment]
Это правильное поведение (что нужно сбрасывать), но было бы более гуманно при включении галки требовать обязательного заполнения версии платформы в карточке при валидации...

**Comment by EmpireSer** [comment]
> Это правильное поведение (что нужно сбрасывать), но было бы более гуманно при включении галки требовать обязательного заполнения версии платформы в карточке при валидации...

По моему мнению это неправильно в том случаи, когда сам GitConverter и так работает на нужной версии и не требуется запускать другую версию (т.е. поле для версии платформы оставляем пустое)

**Comment by marmyshev** [comment]
Да, тут две проблемы:
1.  незаполненная версия - трактуемая как "текущая версия сервера". - тут надо бы доработать
2. Сброс флага "выгрузка изменений" если отключены "очереди" - тут после реализации #70 и перехода хранилища на `8.3.15` (или использования спец.расширения для хака) - эта проблема уйдет
