### ISSUE TITLE
Метки хранилища

### ISSUE THREAD

**Issue by leemuar** [1C-Company/GitConverter#55]
Было бы удобно при конвертации переносить в git и метки хранилища.
Можно в виде git tags, можно в виде комментариев к коммитам

Насколько я помню проблема в том, что отчет по хранилищу не включает информацию по меткам? Последний раз когда смотрел получить их не удавалось программно

**Comment by marmyshev** [comment]
Верно, получить метки хранилища невозможно с помощью отчета.

**Comment by marmyshev** [comment]
Есть идея автоматически добавлять метки новой версии на предыдущий коммит когда меняется версия в файле `src/Configuration/Configuration.mdo` - но наверное такое не всем нужно...

**Comment by zeegin** [comment]
> но наверное такое не всем нужно...

@marmyshev  Я бы заюзал

**Comment by VladFrost** [comment]
@marmyshev Идея годная.

**Comment by leemuar** [comment]
не всем нужно, но как включаемая доп опция - вполне хорошая, нужная задача

**Comment by leemuar** [comment]
предлагаю идею метки при изменении номера версии конфигурации вынести в отдельный ишуз, этот оставить для меток в хранилище (может потом в платформе появится)

**Comment by pumbaEO** [comment]
git tags это не то же самое что и метки в хранилище. tag можно прикреплять только к 1 коммиту и дальше в дереве его не будет видно.

**Comment by pumbaEO** [comment]
@leemuar  
![default](https://user-images.githubusercontent.com/166003/47264700-667ff180-d524-11e8-9f41-50fb945e3ec8.png) тэг можно только к одному коммиту привязать, в истории git они обычно теряются, когда между релизами проходит коммитов 20-30 и уже не понять на какой версии сейчас основано.

**Comment by leemuar** [comment]
@pumbaEO да, все так. Так метки в хранилище же то же самое:

![default](https://user-images.githubusercontent.com/5869791/47267308-94782c80-d54a-11e8-8098-fa8100fe478d.png)

**Comment by nixel2007** [comment]
В хранилище можно поставить одну и ту же метку на несколько коммитов

**Comment by leemuar** [comment]
@nixel2007 Да, верно, хорошее замечание. Это стоит учесть при разработке этого функционала.
Можно будет делать предварительный анализ хранилища и выдавать предупреждение, если есть метки с одинаковыми именами. Можно будет предлагать какие-нибудь алгоритмы переименования таких меток при конвертации.

**Comment by marmyshev** [comment]
@leemuar Если есть идеи как это реализовать - то, имхо, вполне неплохое расширение получится.

**Comment by leemuar** [comment]
@marmyshev ага, идея с расширением понятно. Однако идей как реализовать нет вообще. Несмотря на то, что в настройках формирования отчета по хранилищу есть некий пункт "Включать метки" - выгрузить метки никак не получается

**Comment by marmyshev** [comment]
Этот тикет закрываю, т.к. пока нет способа реализации со стороны Платформы. Если появится - можно открыть опять...
