### ISSUE TITLE
Добавлять метки (git tags) по номеру конфигурации при ее изменении в хранилище

### ISSUE THREAD

**Issue by leemuar** [1C-Company/GitConverter#56]
> Есть идея автоматически добавлять метки (теги) новой версии на предыдущий коммит когда меняется версия в файле src/Configuration/Configuration.mdo - но наверное такое не всем нужно...

https://github.com/1C-Company/GitConverter/issues/55#issuecomment-431327073

Опциональная включаемая возможность

**Comment by Atridis** [comment]
Планирую заняться

**Comment by marmyshev** [comment]
В процедуре `ВыполнитьДействияПередКоммитом` можно зачитать версию конфигурации из файла Configuration.mdo версии и то что уже закоммичен в гите. 
https://github.com/1C-Company/GitConverter/blob/develop/GitConverter/src/CommonModules/КонвертацияХранилища/Module.bsl#L3428

Тогда, можно проверить, что если такого тега с версией нет - то перед коммитом новой версии добавить Тег на текущий коммит

**Comment by marmyshev** [comment]
Полагаю, что нужно бы добавить галку в настройки хранилища. Не забудь привязать видимость галки к флажку "Конвертация в формате EDT"
