### ISSUE TITLE
где Configuration.xml?

### ISSUE THREAD

**Issue by LazarenkoA** [1C-Company/GitConverter#6]
что-то я туплю, но как загрузить это добро в конфигуратор, если нет Configuration.xml?

**Comment by marmyshev** [comment]
Прочитайте раздел https://github.com/1C-Company/GitConverter#Необходимые-компоненты п.1

**Comment by LazarenkoA** [comment]
т.е. только под EDT? Не могли бы выгрузить cf этой конфигурации? Очень прошу

**Comment by marmyshev** [comment]
А в чем проблема скачать EDT по ссылке и сделать cf самому?

**Comment by LazarenkoA** [comment]
так и сделал
