### ISSUE TITLE
Первая версия для выгрузки на самом деле не первая

### ISSUE THREAD

**Issue by leemuar** [1C-Company/GitConverter#61]
Допустим в хранилище конфигурации 10 версий
И я созданию настройку синхронизации в GitConveter
И в поле "Первая версия" указываю 5

Я ожидаю что выгрузятся версии 5, 6, 7, 8, 9, 10
А на самом деле выгрузятся версии 6, 7, 8, 9 , 10, версия 5 будет отсутствовать в выгрузке

**Comment by marmyshev** [comment]
Полагаю, что "копии хранилища" не используются. Да, такую ошибку исправлял для "копий хранилища", тут тоже исправим.
