### ISSUE TITLE
Изменение адреса удалённого хранилища

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/GitConverter#67]
**Существует проблема**
Потребовалось мне поменять адрес удалённого хранилища, без изменения каталога локального. Простым нажатием кнопки прописать адрес хранилища (см. снимок) - не прокатывает. В файле конфигурации локального репозитория остаётся старый, в логе ошибка: "fatal: remote origin already exists." , но поскольку код возврата установки репозитория тоже не анализируется (даже в текущей версии) - кто бы туда глянул.

**Хотелось бы иметь следующую функциональность**
Надо бы сначала его сносить командой: git remote remove origin. Да и анализ результата выполнения команды установки удалённого хранилища тоже очень не плохо было бы добавить.

**Дополнительный контекст**
https://partners.v8.1c.ru/forum/t/1781195/m/1781340

**Comment by leemuar** [comment]
Может не прописывать псевдоним remote в настройки репо, а использовать полный адрес при пуше? Кажется так проще будет управлять адресами: в момент пуша брать настройки адреса и выполнять команду пуша с ним.

**Comment by marmyshev** [comment]
Ну тогда не будет возможности настроить авторизацию по SSH например, или через WCM.
В этом случае просто `git pull` и `git push` удобнее, а для этого нужен remote.
