### ISSUE TITLE
Не работает конвертор

### ISSUE THREAD

**Issue by LazarenkoA** [1C-Company/GitConverter#7]
Произвел настройки согласно описанию
> Скрин настроек
> http://prntscr.com/hxz482

но что-то коммитов в гитхабе нет, что не так я сделал? По нажатию на "Выполнить коммиты" ничего не происходит

**Comment by pumbaEO** [comment]
Такое описание ошибки можно ожидать от пользователя, но и то уровень помощи "лечу по фотографии".  

Опишите, установлен ли git, доступен ли в переменной PATH, добавилися ли список версий справочник, распарсились ли пользователи хранилища, выполнялась ли выгрузка cf файла из хранилища, были ли локальные коммиты в репозиторий.

**Comment by marmyshev** [comment]
Попробую "полечить по фотографии": 
1. Версии хранилища обработаны (4 шт)
2. Версии не закомичены в даже в локальный репозиторий (текущая версия в гит - пуста)
3. Анонимный коммит запрещен - проверьте что для всех пользователей хранилища указаны соответствия email и имен (желательны соответствия тем, что указаны у ваших разрабов в аккаунтах гитхаба) - после можно нажать кнопку "Выполнить коммит" на командной панели.

Еще можно посмотреть список "Версии хранилища" - там красным указаны версии пользователей которые нельзя коммитить.

**Comment by LazarenkoA** [comment]
@marmyshev, спасибо, проблема была именно в отсутствии "информация пользователей"
@pumbaEO, вот видишь, все лечится и даже по фото

**Comment by VladFrost** [comment]
Возможно, ещё причина в том, что gitconverter свои задачи выполняет в фоновом задании, и причина возникновения ошибки не всегда на поверхности.

Вот, например, моя история:
1. После нажатия на кнопку "Запустить конвертацию" ничего не произошло.
2. Тогда я перешёл в "Регламентные и фоновые задания", и там обнаружил многозначительное "При формирования отчета по хранилищу конфигураций возникли ошибки."
![2018-01-10 12_28_07](https://user-images.githubusercontent.com/11960251/34766457-955cf66e-f605-11e7-85bb-a82cc7a5de5b.png)
3. Затем в EDT поставил точку останова `Справочники.ХранилищаКонфигураций.Формы.ФормаЭлемента.Модуль [строка: 93]` как раз там, где вызывается `ЗапуститьКонвертациюНаСервере()`, запустил отладку тонкого клиента и вновь нажал "Запустить конвертацию".
4. После того, как точка сработала, включил автоподключение отладки фоновых заданий в EDT
![2018-01-10 12_21_22](https://user-images.githubusercontent.com/11960251/34767021-d722b05a-f607-11e7-9827-ae165125d793.png)
5. Теперь нужно поставить точку останова непосредственно в фоновом задании, где возникло первоначальное исключение `Общие модули.КонвертацияХранилища.Модуль [строка: 2 083]`, а ещё лучше, чуть раньше, там где вызывается
```bsl
ЗапуститьПриложение(СтрокаКоманды, Параметры.КаталогИсполняемогоФайла, Истина, КодВозврата);
```
![2018-01-10 13_29_11](https://user-images.githubusercontent.com/11960251/34767878-4f9e470e-f60a-11e7-8e71-b19d9fb8efc9.png)

Кстати, в EDT переход к строке по номеру выполняется по `Ctrl+L`, а не `Ctrl+D`

Теперь можно продолжить отладку. Жмём в EDT `Продолжить (F8)` и как только точка отладки в строке 2083 срабатывает, смотрим содержимое переменной `СтрокаКоманды`.

Видим, что 1С:Предприятие запускается с параметрами из txt-файла. Открываем его содержимое и видим, что логи при этом сохраняются в папку, которую мы указали как `Каталог выгрузки версий`, а сам файл называется `log.txt`. Содержимое файла подскажет, что пошло не так в процессе запуска конвертации.

В моём случае это сообщение
```
Несоответствие версий клиентского приложения и сервера хранилища конфигурации.
(Версия клиентского приложения:  8.3.11.2954
Версия сервера хранилища конфигурации: 8.3.11.2899)
```

Следовательно, я забыл прочитать инструкцию и заполнить константу "Путь к версиям платформы на сервере"  :)
