### ISSUE TITLE
Использование оптимизаций в 8.3.15

### ISSUE THREAD

**Issue by marmyshev** [1C-Company/GitConverter#70]
**Существует проблема**
Для выгрузки изменений текущей версии необходимо подставлять файл состояния объектов предыдущей версии. Файл `ConfigDumpInfo.xml` до 8.3.15 можно было получать только выгрузив предыдущую версию. 

Это накладывает ограничение: все версии должны выгружаться строго последовательно, иначе версия будет быть выгружена полностью, что не хорошо и нагружает процессор излишне, тратится лишнее время.

**Хотелось бы иметь следующую функциональность**
[Использование новых возможностей выгрузки Платформы 8.3.15. ](https://its.1c.ru/db/v8315doc#bookmark:adm:TI000000527)

> * -configDumpInfoOnly ‑ указанием данного параметра приводит к тому, что при выгрузке формируется только файл версий (ConfigDumpInfo.xml). Если в командной строке будет указан параметр -format, то файл версии будет сформирован для указанного формата выгрузки. По умолчанию файл версий формируется для иерархического формата выгрузки.

При получении версии из хранилища - можно выгружать файл `ConfigDumpInfo.xml` с помощью нового колюча `-configDumpInfoOnly` - это позволит завести несколько версий выгрузки и выгружать только изменения "по-честному" параллельно.

Так же можно будет выгружать изменения не используя "Очереди выгрузки" (снимается ограничение)

**Расширение или улучшение?**

Это улучшение конфигурации 1С:ГитКонвертер улучшает конвертацию на новой платформе 8.3.15.

Т.к. новые возможности будут доступны только начиная с **8.3.15** - возможно стоит сделать специальное расширение которое позволит делать выгрузку `ConfigDumpInfo.xml` на версии 8.3.15 и продолжить выгрузку на более низких версиях. Нужно учесть что заголовке xml прописывается версия формата, которую невозможно загрузить на младших версиях - нужно сделать фикс версии если формат не поменялся.

**Comment by leemuar** [comment]
О каких улучшениях идет речь? Что в 15й версии планируется интересного для конвертера?

**Comment by marmyshev** [comment]
Тут придется подождать публикации бета-версии 8.3.15 :( или если вдруг анонс на зазаркалье сделают (но имхо, слишком мелко для зазеркалья)
