### ISSUE TITLE
Поддержка конвертации нескольких веток конфигурации на разных версиях EDT

### ISSUE THREAD

**Issue by Zavailik1365** [1C-Company/GitConverter#73]
Если в конфигурации поддерживается несколько веток, необходимо иметь возможность указывать версию EDT для конвертации.

Проблема связана с тем, что при переходе на новую версию платформы необходимо обновлять и версию EDT, после чего требуется выполнить проверку корректности перехода. Хотелось бы избежать проверки для веток, которые работаю на старых версиях платформы.  

Реализация улучшения будет выполнена в виде расширения и доработок конфигурации.

Что измениться в конфигурации:
1. В процедуре `КонвертацияХранилища.ИмпортироватьВерсиюВEDT` формирование переменой `СтрокаКоманды` будет вынесено в отдельную функцию;

Что будет содержать расширение:
1. В справочник `ХранилищаКонфигураций` будет добавлен реквизит `ВерсияEDT`
2. В модуле `КонвертацияХранилища` будет переопределена процедура формирования `СтрокаКоманды`. При установке значения переменой будет учтена версия EDT.

**Comment by marmyshev** [comment]
Предлагаю сделать расширением:
вот тут 

```
СтрокаКоманды = "ring edt workspace import --workspace-location ""%РабочийКаталог%"" --configuration-files ""%КаталогФайловКонфигурации%"" --project ""%КаталогПроектаEDT%"" --version %ВерсияПроектаEDT% >> %ИмяФайлаЛогов% 2>&1";
```
https://github.com/1C-Company/GitConverter/blob/feature/issue-69-repo-platform-version/GitConverter/src/CommonModules/КонвертацияХранилища/Module.bsl#L1415

нужно бы сделать явное указание версии если она задана в настройках для хранилища например для 1.10

```
СтрокаКоманды = "ring edt@1.10.0 workspace import --workspace-location ""%РабочийКаталог%"" --configuration-files ""%КаталогФайловКонфигурации%"" --project ""%КаталогПроектаEDT%"" --version %ВерсияПроектаEDT% >> %ИмяФайлаЛогов% 2>&1";
```

в идеале можно было бы вывести список установленных модулей командой
`ring help modules > log.txt` и прочитать, если модулей EDT больше чем 1 - тогда требовать в проекте обязательность заполнения версии - тогда это можно даже не расширением а встроить в конфигурацию!

**Comment by marmyshev** [comment]
@Zavailik1365 может стоит сделать не через расширение, доработкой. Например, сделать ФО "ИспользоватьНесколькоВерсийEDT" и те кто хотят включить эту ФО - могут использовать несколько версий. В справочнике ее сделать обязательной если включена.
По умолчанию будет одна версия.

Так же по кнопке "Проверить версию" в карточке делать запрос `ring help modules > log.txt` количества модулей - и если версий несколько автоматически включать ФО. 

Тогда, имхо, будет удобно и прозрачно для пользователя...
