### ISSUE TITLE
При ошибках в журнал регистрации записывать вывод файла log.txt

### ISSUE THREAD

**Issue by pumbaEO** [1C-Company/GitConverter#8]
#7 

> Видим, что 1С:Предприятие запускается с параметрами из txt-файла. Открываем его содержимое и видим, что логи при этом сохраняются в папку, которую мы указали как Каталог выгрузки версий, а сам файл называется log.txt. Содержимое файла подскажет, что пошло не так в процессе запуска конвертации.

**Comment by artbear** [comment]
Да, разбирать проблемы станет намного проще.
Вывод от 1С обязательно нужно показывать.
т.к. очень много ошибок при первичной настройке.
а в дальнейшем будут только редкие странные ошибки, которые без логов не разберешь.

**Comment by marmyshev** [comment]
А зачем смешивать ошибки ЖР - т.е. ошибки самой конфигурации ГитКонвертера с ошибками пакетных операций во внешних системах (гит, хранилище, базы итд)?

Все-таки хотелось бы (цель), чтобы в ЖР ГитКонвертера не было ошибок :)
а логи/ошибки внешних систем - это штука не зависящая от ГитКонвертера.

**Comment by pumbaEO** [comment]
1. Ну как-бы единое окно в конфигурации идет. 
2. В консольных приложениях это срач в стандартный вывод (в зависимости от уровня логгинга), а тут по факту показать сразу направление  ну или же подсказку, что доп. логи смотри по такому-то пути. 
3. Логи внешних систем необходимы в базе при возникновении ошибки, при работе в штатном режиме они не нужны.

**Comment by VladFrost** [comment]
> Все-таки хотелось бы (цель), чтобы в ЖР ГитКонвертера не было ошибок :)

Полагаю, что цель, всё-таки, не замаскировать ошибки, а облегчить пользователю диагностику, чтобы не приходилось проходить сложный квест по расследованию как в https://github.com/1C-Company/GitConverter/issues/7

**Comment by pumbaEO** [comment]
Вот тут бы и пулл сделать, пару строк перед вызовом исключения сделать, но ... #2

**Comment by artbear** [comment]
Дмитрий, мы по нашему опыту работу в gitsync (c гитом и хранилищем) знаем о довольно частых ошибках при первичных настройках или редких ошибках в уже настроенных системах.

Если не добавить диагностики, как выполнять анализ ошибок.
Повторение ошибки при повторном запуске не всегда ведь возможно.

**Comment by Stepa86** [comment]
@marmyshev Это для удобства нужно. Все таки основные целевые пользователи очень слабо знают гит, пакетный режим, пуш из под учетки сервера итп. И когда что то пошло не так - это превращается в тот еще квест.

Хочется сразу в продукте понимать, что коммиты не выгружены и кто виноват. У меня обычно такие ошибки в аналогичном продукте:
- Различные версии 1С
- Проблемы с доступом к базе, куда выгружается версия хранилища (место закончилось, база переехала, захвачено параллельным процессом или еще что нить такое. У меня статичная база, а не создаваемая временно)
- Отсутствие данных о пользователе, выполнившем коммит
- Выгрузка тупо повисла без понятных причин - решается удалением процесса
- Пуш ожидает авторизации для гитхаба
- Репо гита для выгрузки на самом деле не является репозиторием гита
- Коммит отскочил с ошибкой "Нечего коммитить"
- Коммит не прошел, т.к. гит репо заблокирован (привет от сорцтри такой)
- прочие сюрпризы

**Comment by marmyshev** [comment]
@Stepa86 

> Все таки основные целевые пользователи очень слабо знают гит

Вероятно, эти пользователи не будут тогда пытаться скачать эту конфигурацию в исходных кодах с GitHub'а :) 

В общем, мнения разделились: кому-то нужно ЖР -> log.txt, а кому-то нужно log.txt -> в ЖР и еще спец. интерфейс диагностики.

**Comment by marmyshev** [comment]
@VladFrost 

> > Все-таки хотелось бы (цель), чтобы в ЖР ГитКонвертера не было ошибок :)

> Полагаю, что цель, всё-таки, не замаскировать ошибки

цель - чтобы не было ошибок самой конфигурации ГитКонверетра - безошибочная работа инструмента - это все-таки хорошая цель :)

**Comment by Stepa86** [comment]
@marmyshev Скачать то не проблема, особенно по инструкции с ИТС. А вот когда почему то не работает - хочется знать причину. Особенно когда еще недавно работало.

Разделения мнений не вижу. Все хотят видеть один общий лог. Думаю, оптимальнее всего будет запись в log.txt в том числе и действий гитконвертера. И открытие по кнопке этого файлика из формы хранилища.

Ну и полный экстаз, если сам гитконвертер будет оповещать об ошибках в интерфейсе (красненьким в шапке "У вас тут несколько версий не выгрузилось из-за незаполненности комментария") и уметь слать на почту ошибки.

**Comment by pumbaEO** [comment]
Опять какой-то срач по поводу "логов мало не бывает", по факту суть задачи или в https://github.com/1C-Company/GitConverter/blob/master/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L2083  добавить
```
ОписаниеОшибки = СтрШаблон("При формирования отчета по хранилищу конфигураций возникли ошибки. см %1", Параметры.ИмяФайлаЛогов);
ВызватьИсключение ОписаниеОшибки;
```
Это уже необходимый минимум, что-бы понимать куда смотерть. 
Или же делаем в попытке "Новый ЧтениеТекста(Параметры.ИмяФайлаЛогов)" и записываем в журнал регистрации с текстом, что-бы не приходилось открывать текстовый файл.

Ну или уже как извращение создаем свой регистр, там фиксируем все задания выполняемые в фоне и их логи, при удачном/неудачном завершении. Добавляем регл. задание по очистке этого регистра, потом добавляем константу в которой храним количество дней/задач/версий которые надо оставлять истории регистра...

**Comment by marmyshev** [comment]
"Общий лог" - это понятно, это, вероятно, нужно для диагностики. Подумаем. Все предложения услышаны :)

Общего файла лога `log.txt` не будет - ибо "файл" это не транакционная и конкурентная вещь. Когда у вас тысячи потоков работают - общий на всех файл - это очень нехорошо.

**Comment by Infactum** [comment]
> Общего файла лога log.txt не будет - ибо "файл" это не транзакционная и конкурентная вещь. Когда у вас тысячи потоков работают - общий на всех файл - это очень нехорошо.

Логи буфферизуются, буффер переодически сбрасывается одним потоком на диск. Стандартное решение в логгерах.

**Comment by pumbaEO** [comment]
>  Общего файла лога log.txt не будет - ибо "файл" это не транакционная и конкурентная вещь.
Так он же у вас в параметрах задания указан Параметры.ИмяФайлаЛогов. А если чуть ниже взгляд опустить в коде, то можно увидеть https://github.com/1C-Company/GitConverter/blob/master/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L2166 

Просто в одном месте не скопипастили и задача превращается в выделение отдельной процедуры и растановки ее вызова. 

p.s.: Все предложения услышаны - это так "по-партнерски", что аж тошно.

**Comment by VladFrost** [comment]
@marmyshev Дмитрий, поясните, пожалуйста, вы здесь пишете:
> Когда у вас тысячи потоков работают - общий на всех файл - это очень нехорошо.

А в [README.md](https://github.com/1C-Company/GitConverter#%D0%9E%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D0%B8-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F) указано, что
> Начиная с версии Платформы 8.3.10 возможно использовать выгрузку изменений - для этого необходимо выгружать версии строго последовательно и не рекомендуется создавать более одной очереди на выгрузку.

Получается, что в gitconverter есть два режима выгрузки:
1. многопоточная, полная,
2. однопоточная, инкрементная.

А какой режим вы рекомендуете использовать?

**Comment by pumbaEO** [comment]
@VladFrost  до поддержки платформой инкрементной выгрузки, на конфигурацию типа ERP для выгрузки в гит одной версии тратилось от 30 минут до часа. С инкриментной выгрузкой от 5 минут до 10. Соотвественно, 1000 версий  раньше могло синхронизироваться месяц, сейчас до 6 дней. 

Поэтому инкрементная имхо предпочтительней, т.к. в многопоточной потом еще долгое время всякие rebase делать уже на стороне гита и заморачиваться с этим не имеет смысла.

**Comment by marmyshev** [comment]
@VladFrost 

> Получается, что в gitconverter есть два режима выгрузки:
> 
> 1. многопоточная, полная,
> 2. однопоточная, инкрементная.
> 
> А какой режим вы рекомендуете использовать?

Давайте определимся с понятиями: инкрементальная выгрузка Конфигуратора - это **не** однопоточная работа конфигурации ГитКонвертера: получение из хранилища можно сделать в нескольких потоках, поток (он же Фоновое Задание) выгрузки, поток обработки метаданных, и поток коммита - т.е. минимум 4.

А дальше - удобство конкретно этой конфигурации в том, что, *почти*, нет ограничений на масштабирование и параллелизацию.
Но какое руководство компании сможет выделить денег на сервер чтобы запустить 10k высоко-нагружающих процессор потоков? :) сколько для этого нужно ядер CPU? Сколько будут стоить такие SDD диски? Ладно, 5-10Тб оперативки это нынче не проблема :) (шутка)

Итого, совсем однопоточного режима - вообще нет. Для этого есть другие утилиты конвертации в гит (на гитхабе найдете :).

### Как параллелить инкрементальную выгрузку?

1. Определитесь, зачем это надо? Имхо, надо когда есть  **> 30k** истории таких конфигураций как ERP, БП итд. и нужно как можно быстрей получить историю. Или ваши разрабы фигачат >500 версий в сутки в хранилище 1С?
2. Есть ли реально оборудование для этого? CPU, SSD/SSD-RAID?, RAM
3. Нужно запустить Х очередей на выгрузку установив для каждой из очередей соответствующий интервал работы:
    * Первая очередь - работает с 1 по 50 версию, выгружая инкрементальной
    * Вторая очередь - работает с 51 по 100 версию
    * И так далее...
4. Нужно понимать что эти очереди должны обеспечиваться параллельным получений версий из хранилища (или из копий)
5. На обработку выгруженных версий ограничений параллельности нет.

Не забываем про очередь к диску и произвоидительность дисковой системы... :)
