### ISSUE TITLE
Не отправляются коммиты в локальный каталог гит

### ISSUE THREAD

**Issue by LazarevRoman** [1C-Company/GitConverter#88]
**Описание ошибки**
Запускаем обработку по конвертации хранилища конфигурации в локальные репо и после создания истории из хранилки, пытаемся выполнить коммит. Ничего не происходит

**Сценарий воспроизведения**
1. Заполняем все настройки в справочнике хранилище конфигурации. 
2. Указываем также адреса репозитория гит.
3. Нажимаем "запустить конвертацию"
4. После выполнения шага 3, нажимаем на кнопку "выполнить коммиты".

Ничего не происходит, коммит не помещается. В истории версии хранилища статус - метаданные получены. 

**Ожидаемое поведение**
Статус в  истории версии хранилища статус - версия помещена должно быть

**Скриншоты, логи, ЖР**
* скриншоты очень сильно помогают
* добавте логи из Журнала Регистрации, из лог-файлов (убедитесь что они не содержат приватной информации)
01.03.2019 13:50:50 Начало получения коммитов с Git-сервера
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

01.03.2019 13:50:51 Окончание получения коммитов с Git-сервера
Код возврата: 1
01.03.2019 13:50:51 Окончание получения коммитов с Git-сервера
Получение коммитов (git pull) с Git-сервера выполнен не успешно. Необходимо проанализировать лог, устранить причину.
01.03.2019 13:50:52

**Дополнительная информация**

Обсуждали эту ошибку в чате Телеграмм. Решение, сначала убрать из адреса репо гит - адрес, запустить конвертацию и потом нажать на кнопку выполнить коммиты. Тогда все проходит корретно

**Comment by a-perminov** [comment]
Версия 1.0.6.1.
Проблема повторяется.

Как решить:
 - запустить консоль git
 - выполнить
`git branch --set-upstream-to=origin/master master`
