### ISSUE TITLE
Ошибка перехода в каталог командой CD

### ISSUE THREAD

**Issue by pumbaEO** [1C-Company/GitConverter#9]
https://github.com/1C-Company/GitConverter/blob/7e6e1591a3628b9ffe958347fa3db649dcb6289f/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L1651

1. Команды в линукс регистрозависимые, поэтому необходимо `cd` 
2. Для windows необходимо добавить ключ /D для возможности смены диска.

**Comment by nixel2007** [comment]
> поэтому необходимо CD

может все же `cd`?

**Comment by pumbaEO** [comment]
да `cd` исправил описание задачи.

**Comment by marmyshev** [comment]
да, я как раз уже исправил - в след. версии будет.

**Comment by pumbaEO** [comment]
Так это же git, можно и в develop кинуть коммиты, не дожидаясь релиза следующей версии.
