### ISSUE TITLE
На виндовс сервере с английской локализацией наблюдается ошибка формирования записей файла git_command_*

### ISSUE THREAD

**Issue by fenixnow** [1C-Company/GitConverter#91]
При формировании записей файла, русские символы заменяются знаком "?"

соответственно строка общего модуля КонвертацияХранилища(3376) 

```
Если ЭтоWindowsСервер Тогда
		ФайлКоманды.Записать(ИмяФайлаКомандыGit, КодировкаТекста.OEM);
	Иначе
		ФайлКоманды.Записать(ИмяФайлаКомандыGit, КодировкаТекста.Системная, Символы.ПС);
	КонецЕсли;
```

Предложу поменять кодировку на UTF8

У меня решилась проблема

**Comment by fenixnow** [comment]
эх... при такой кодировке дальше вылазиет ошибка при выполнении батника.... :( черт

**Comment by VladFrost** [comment]
В батник, наверное, надо вставлять первой строкой `chcp 65001`?

**Comment by leemuar** [comment]
Я правильно понял, русские символы где-то в файловых путях?

**Comment by fenixnow** [comment]
> Я правильно понял, русские символы где-то в файловых путях?

Да, все правильно. Все русские символы заменяются вопросиками.

**Comment by leemuar** [comment]
Возможно связано с #92 92

**Comment by marmyshev** [comment]
@fenixnow Что в итоге сделали чтобы пофиксить? Я правильно понял (из связанной ошибки #92), что настроили профиль пользователя (под которым запущен 1С) чтобы был на русском?

**Comment by fenixnow** [comment]
Нет, оставил кодировку utf8 а в формирование файла с командами добавил chcp 65001.
Пока полет номальный

**Comment by marmyshev** [comment]
@fenixnow пул-реквест сделаешь?
