### ISSUE TITLE
Ошибка при изменении регистра символа в имени объекта метаданных

### ISSUE THREAD

**Issue by svcoder1980** [1C-Company/GitConverter#92]
**Описание ошибки**
Если в хранилище поместить 2 версии, в 1-ой объект метаданных, а во второй он же но с другим регистром символов в имени будет создан некорректный репозитарий Git с точки зрения EDT

**Сценарий воспроизведения**
1. Создать чистую базу, добавить в нее общую форму Форма1 с пустой процедурой ПриСозданииНаСервере
2. Создать новое хранилище и подключить к нему созданную базу
3. Захватить хранилище и поменять имя на форма1 и добавить общую форму Форма2, применить изменения в хранилище
4. Сформировать репозитарий Git с помощью GitConverter
5. Импортировать репозиторий в EDT
6. Открыть окно неподготовленных изменений и обнаружить там объекты с которыми ничего нельзя сделать

**Ожидаемое поведение**
Должей создаваться корректный репозитарий. Сейчас получается, что удаление объекта Форма1 попала в commit, а удаление подчиненных ему формы и модуля нет

**Скриншоты, логи, ЖР**
![2019-03-16_13-57-05](https://user-images.githubusercontent.com/39004144/54474249-c472e580-47f3-11e9-8e80-3f87decf6a47.png)

**Comment by svcoder1980** [comment]
Ошибка была связана с записью текстового документа команд Git в кодировке OEM при использовании английской версии Windows 10. При этом в файле команд все русские буквы заменялись на ? и это как-то работало, видимо из-за того что Git воспринимает ? как шаблон имени файла.
Копирование настроек на экран приветствия и для новых профилей решило проблему

**Comment by leemuar** [comment]
@svcoder1980 может все-таки это имеет смысл пофиксить в Конвертере? У нас уже есть несколько людей, работающих с конвертером на англ винде

**Comment by leemuar** [comment]
Возможно связано с #91
